<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="20.460" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2023-05-21T15:37:04" tests="0" file="cypress/e2e/secondTest.cy.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2023-05-21T15:37:04" tests="1" time="20.444" failures="1">
    <testcase name="Test log out verify use can log out successfully" time="6.422" classname="verify use can log out successfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (webpack:///./cypress/e2e/secondTest.cy.ts:9:26)]]></failure>
    </testcase>
  </testsuite>
</testsuites>